import "@/styles/globals.scss";
import { Providers } from "../redux/provider";
import local from "next/font/local";

const yakh = local({
  src: "../styles/fonts/YekanBakh-Regular.ttf",
  preload: true,
  adjustFontFallback: "Times New Roman",
});

export const metadata = {
  title: "Miras",
  description: "Generated by Next js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={yakh.className}>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
